### PR TITLE
- Added test for self alias.

### PR DESCRIPTION
**Pull request by manwar**
Hi,

Please review the PR.

Many Thanks.
Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Review by zackvolz — APPROVED** [review]

**Comment by autarch** [comment]
The code looks fine. I've started on a style guide for all repos in this org at https://github.com/houseabsolute/houseabsolute-style-guide

The particular issue with this PR is the commit message's use of needless punctuation. Please remove that and amend the existing commit. Then I will merge it. Thanks!

**Comment by manwar** [comment]
Commit message amended as requested.

**Comment by autarch** [comment]
Can you rebase so this is just a single commit?

**Comment by manwar** [comment]
rebased it, please review it now.
not sure if I did it correctly. first time ever did rebase. I always do merge.

**Comment by manwar** [comment]
This PR can be closed without merge.

**Pull request closed without merging**
