### PR TITLE
Lazy load of locale data

### PR DESCRIPTION
**Pull request by sergle**
Hi
In my code I have found that after removing unused locales it frees ~10Mb of RSS memory of process.
Here I'm trying to load locale data on demand - similar to DateTime::TimeZone
Commits includes full list of generated pm-per-locale files.

### CODE REVIEW

**Comment by autarch** [comment]
I wonder if there's a way to do save memory without having to move everything out into separate files. For example, rather than putting the locale data in `__DATA__` it could go in the file some other way and we could manually read the data using `seek` as needed.

**Comment by autarch** [comment]
Hmm, I wrote the previous comment and then I remembered e1a4063917a4a9de3b6b404ae7e9d71bfff726a0

**Comment by sergle** [comment]
Maybe just store data into separate file, not in DATA. But the one problem I see - how to find it's location from code. Any suggestions?

**Comment by autarch** [comment]
I was thinking of that too. It could even be one file per locale. Mostly what I'd like to avoid is shipping hundreds of namespaces, since each namespace you create also uses memory. I think `File::ShareDir` would be the right tool for this job.

**Comment by sergle** [comment]
@autarch could you help me with Dist::Zilla and File::ShareDir? How to use local directory during tests? How to install this directory?
I have never used Dist::Zilla before.

**Comment by autarch** [comment]
I think you just need to add `[ShareDir]` to the `dist.ini` - see https://metacpan.org/pod/Dist::Zilla::Plugin::ShareDir

**Comment by sergle** [comment]
Sorry for the mess with commits. Should I create a new PR from the fresh fork?

**Comment by autarch** [comment]
You can just rebase the branch.

**Comment by autarch** [comment]
I ended doing my own version of this in #17. Thanks for suggesting this!

**Pull request closed without merging**
